version: "3.9"
services:
  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=auto_shop
      - GDATA=/var/lib/postgresql/data
    volumes:
      - ./db/auto_shop/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
  app:
    image: before-getting-job
    container_name: before-getting-job
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/auto_shop
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
    ports:
      - "127.0.0.1:80:8081"
    depends_on:
      - db